### ISSUE TITLE
[NPS] Add nearbuilders projects

### ISSUE THREAD

**Issue by elliotBraem** [NEAR-DevHub/race-of-sloths#138] opened 2024-07-09 18:04 UTC
How can we address you: Build DAO

Your project's GitHub: https://github.com/nearbuilders

bos-workspace
near-bos-webcomponent
gateway
near-api-rs
near-social-js

**Tell us more about your project and why you want to join the Race:** We are building support systems for open web projects, and it would be great to engage developers with fun rewards. These are five distinct projects that are all built on NEAR tech stack.

**Comment by ftdgoodluck** [comment] 2024-07-09 18:41
closing as a duplicate of #137

**Closed** 2024-07-09 18:41 UTC
Labels: duplicate, New-project-submission
